### ISSUE TITLE
OPEN CV Error..

### ISSUE THREAD

**Issue by anonymousm3** [adeept/adeept_picarpro#10]
Hi, I am having this error despite of following every instuctions on the manual.

![image](https://user-images.githubusercontent.com/29025009/178240350-441910e6-6e40-48d0-a72c-649d849ce89d.png)

Please take time to check the error as we needed this project for upcoming event and presentation .. Thank you so much

**Comment by anonymousm3** [comment]
ERROR RESPONSE 

pi@raspberrypi:~ $ cd adeept_picarpro/server
pi@raspberrypi:~/adeept_picarpro/server $ sudo killall python3
python3: no process found
pi@raspberrypi:~/adeept_picarpro/server $ sudo python3 webServer.py
......................pause..........................
mpu6050 connected, PT MODE ON
......................pause..........................
Starting camera thread.
select timeout
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/adeept_picarpro/server/base_camera.py", line 94, in _thread
    for frame in frames_iterator:
  File "/home/pi/adeept_picarpro/server/camera_opencv.py", line 446, in frames
    if cv2.imencode('.jpg', img)[0] :
cv2.error: OpenCV(3.4.3) /home/pi/opencv-python/opencv/modules/imgcodecs/src/grfmt_base.cpp:145: error: (-10:Unknown error code -10) Raw image encoder error: Empty JPEG image (DNL not supported) in function 'throwOnEror'
